name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Cargo Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust 1.86.0
        uses: dtolnay/rust-toolchain@1.86.0

      - name: Install protoc
        run: sudo apt-get install -y protobuf-compiler

      - name: Run tests
        run: cargo test
